### ISSUE TITLE
No registration email being sent

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/wallabag2_ynh#154]
I have enabled registrations via:
`/var/www/wallabag2/app/config/parameters.yml`  and `fosuser_registration: true`

Butt no registration email is being sent by the server.

This is my parameters.yml file:

```
# This file is a "template" of what your parameters.yml file should look like
parameters:
    # Uncomment these settings or manually update your parameters.yml
    # to use docker-compose
    #
    # database_driver: %env.database_driver%
    # database_host: %env.database_host%
    # database_port: %env.database_port%
    # database_name: %env.database_name%
    # database_user: %env.database_user%
    # database_password: %env.database_password%

    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: ~
    database_name:  wallabag2
    database_user: wallabag2
    database_password: 90Ir1vTEMYCLi2GuOEtkdFb5
    # For SQLite, database_path should be "%kernel.project_dir%/data/db/wallabag.sqlite"
    database_path: null
    database_table_prefix: null
    database_socket: null
    # with PostgreSQL and SQLite, you must set "utf8"
    database_charset: utf8mb4

    domain_name: https://bag.trom.tf/
    server_name: "Your wallabag instance"

    mailer_transport:  smtp
    mailer_user:       ~
    mailer_password:   ~
    mailer_host:       127.0.0.1
    mailer_port:       false
    mailer_encryption: ~
    mailer_auth_mode:  ~

    locale: en

    # A secret key that's used to generate certain security-related tokens
    secret: CHANGE_ME_TO_SOMETHING_SECRET_AND_RANDOM

    # two factor stuff
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org

    # fosuser stuff
    fosuser_registration: true
    fosuser_confirmation: true

    # how long the access token should live in seconds for the API
    fos_oauth_server_access_token_lifetime: 3600
    # how long the refresh token should life in seconds for the API
    fos_oauth_server_refresh_token_lifetime: 1209600

    from_email: webmaster@trom.tf

    rss_limit: 50

    # RabbitMQ processing
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10

    # Redis processing
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null

    # sentry logging
    sentry_dsn: ~

```
